# Generated by Django 5.1.5 on 2025-02-07 11:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_alter_shortenedurl_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, max_length=40, unique=True),
        ),
    ]
