# Generated by Django 5.1.5 on 2025-02-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0004_pagevisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
