# Generated by Django 5.1.5 on 2025-02-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploaddedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=256, verbose_name='File Name')),
                ('s3_file_key', models.CharField(max_length=512, verbose_name='S3 File KEY')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('uploader_ip', models.CharField(max_length=50, null=True, verbose_name='Uploader IP')),
                ('size', models.FloatField(verbose_name='Fole Size')),
            ],
        ),
    ]
