# Generated by Django 5.1.5 on 2025-02-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_uploaddedfile_content_type_alter_uploaddedfile_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddedfile',
            name='slug',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Slug'),
        ),
    ]
