# Generated by Django 5.1.5 on 2025-02-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_uploaddedfile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddedfile',
            name='short_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Short URL'),
        ),
    ]
